# pyproject.toml

[build-system]
requires = ["setuptools>=61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "DeSide"
version = "2.0.0a0"
description = "A unified DEep-learning and SIngle-cell based DEconvolution method for solid tumors"
readme = "README.md"
license = { file = "LICENSE" }
requires-python = ">=3.9"
authors = [
    { name = "OnlyBelter", email = "onlybelter@outlook.com" },
]
keywords = [
    "DeSide",
    "RNA-seq",
    "deconvolution",
]
classifiers = [
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: BSD License",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Typing :: Typed",
]
dependencies = [
    "torch>=2.0.0",
    "lightning==2.5.1",
    "scikit-learn>=0.24.2",
    "anndata>=0.8.0",
    "scanpy==1.11.5",
    "pandas>=1.5.3",
    "numpy>=1.22",
    "scipy",
    "umap-learn==0.5.6",
    "matplotlib>=3.6,<3.10",
    "seaborn>=0.11.2",
    "bbknn>=1.5.1",
    "SciencePlots",
    "tables>=3.6.1",
    "build",
    "sphinx>=6.0",
    "myst-parser>=0.13.6",
    "fsspec",
    "h5py",
    "jinja2>=3.1",
    "numba>=0.57",
    "pyyaml",
]
#dynamic = ["version"]

[project.urls]
#Documentation = "https://deside.readthedocs.io/"
Homepage = "https://github.com/OnlyBelter/DeSide"
Source = "https://github.com/OnlyBelter/DeSide"
Tracker = "https://github.com/OnlyBelter/DeSide/issues"

# https://realpython.com/pypi-publish-python-package/#version-your-package
[tool.bumpver]
current_version = "2.0.0a0"
version_pattern = "MAJOR.MINOR.PATCH[PYTAGNUM]"
commit_message = "bump version {old_version} -> {new_version}"
commit = true
tag = true
push = false

[project.scripts]
deside = "deside.cli.main:main"

[tool.bumpver.file_patterns]
"pyproject.toml" = [
    'current_version = "{version}"',
]
"setup.py" = [
    "{version}",
    "{pep440_version}",
]
"README.rst" = [
    "{version}",
    "{pep440_version}",
]
"README.md" = [
    "{version}",
    "{pep440_version}",
]

# Setuptools configuration
[tool.setuptools.packages.find]
where = ["."]
include = ["deside*"]
exclude = ["tests*", "docs*", "examples*"]

[tool.setuptools.package-data]
"deside.configs" = ["*.yaml"]
